### ISSUE TITLE
Final project questions

### ISSUE THREAD

**Issue by drefiuza** [uchicago-mobi/2015-Winter-Forum#108]
Hi Andrew,

I've been thinking about the final project and have some questions.

Could you provide examples of what a good project looks like; something with an ideal scope and difficulty level? I’d also be curious to know what types of projects you consider to be too easy or too complicated.

Also, how many weeks will we have to work on this project?

Thanks!

Andre

**Comment by johnnypaper** [comment]
I'd also like to ask a couple of things in addition since Andre has brought this up...

For those of us graduating, how long will we have and when will the due date be?

If we are planning to write an app for the store that will be available for a production website, who will have access to the code and will be grading the final projects?  For instance if there are routes that reply to json requests that we would prefer not to be known, or other portions of the app we would rather not be seen in code eg authentication etc, how can we handle those situations?  Or should I consider an idea that has nothing to do with production if I would rather not have the code available?

Thanks

**Comment by yiqin** [comment]
I think TestFlight Beta Testing (https://developer.apple.com/testflight/) is perfect for the course project. It's super easy to use. It allows us to install apps before you release them on the App Store. The review process of iOS apps is really painful, and it usually takes up to 14 days.

Do we use TestFlight Beta Testing?

**Comment by johnnypaper** [comment]
Hmmm...that looks pretty good there.  I think that is new? I don't remember that and yep that process is very irritating or can be with approval.  A binary version is a good thing and looks like that makes it possible.  The question is...Will a binary version of the app be accepted for grading?

**Comment by yiqin** [comment]
TestFlight Beta Testing is integrated into iOS 8 perfectly. We just need to upload it to itune connect. No more actions are needed. Before that, we have to  generate dSym and upload dSym separately to another website. But now, it becomes quite simple. In the class, we can download others' app through TestFlight Beta Testing.

**Comment by tabinks** [comment]
I will go over everything related to the final project during next lecture.  You will have to submit the code for assignment, not a binary.  The instructors will need access to any iOS related code, you should factor this into any choices you make about what your project will be.  If you choose to interact with a server, we will not look at the server code.  We will just ensure that data is handled properly in the app.

@johnnypaper I will find out when the grades for graduating students are due.  I will make accommodations for these students.
