### ISSUE TITLE
NSUserDefaults Persistence

### ISSUE THREAD

**Issue by johnnypaper** [uchicago-mobi/2015-Winter-Forum#131]
I have the app wired for a NSMutableDictionary of NSDictionaries in the AppDelegate didFinishLaunchingWithOptions method.  Each dictionary in the dictionary has the Title and Link so that I can populate the Title in the bookmarks and have the Link to navigate to in the details.

I haven't tested the second sentence yet, but that is how it is setup and I can retrieve them.   However, I was under the impression these entries were supposed to persist across sessions...does this not occur when using the simulator?  As of this moment that's what I'm trying to solve and it doesn't appear that they do.

Thanks.

**Comment by bobby-digital-23** [comment]
Hi Brad,

Are you using NSUserDefaults?

You might also find this helpful:
https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/iOS_Simulator_Guide/TestingontheiOSSimulator/TestingontheiOSSimulator.html#//apple_ref/doc/uid/TP40012848-CH4-SW1

Best,
Bobby

**Comment by bobby-digital-23** [comment]
Sorry, that posted from my phone before I typed it out completely, d'oh!

The question should be are you using NSUserDefaults AND is it being written to before the simulator exits? Pressing the stop button (instead of the Home button in the simulator) in XCode might cause you problems.

This might help you:
http://stackoverflow.com/questions/2622754/why-is-nsuserdefaults-not-saving-my-values/2622940#2622940

You are correct though - NSUserDefaults should persist in the simulator assuming they are written out properly.

**Comment by tabinks** [comment]
Defaults will persist in simulator.  Just log them out and you will see this.  You can delete them by deleting app from simulator....for testing purposes.

**Comment by JRam13** [comment]
Or calling `removeObjectForKey:`

**Comment by JRam13** [comment]
You can force NSUserdefaults to write to disk immediately by doing the following:

``` objc
NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
[defaults setObject:@"xxxxxxxx" forKey:@"name"];

[defaults synchronize];
```

**Comment by johnnypaper** [comment]
I've got all of that and written that code too in 5 ways and NSLogged until my eyes bled.  So...again, this must just be my machine.  Thanks for the help though.

EDIT: after absolutely wasting hours on this problem...it seems as though it was correct the whole time but the simulator doesn't have a home button so using Control + Shift + h will go to menu screen and the choices are still there.  For some reason Apple feels it's a great idea to have a 3 button shortcut instead of just put the home button on the screen like a real device.

I ran out, but I'm going to have to get another bottle:

![iosexcedrin](https://cloud.githubusercontent.com/assets/6334967/6201437/ea80937a-b46e-11e4-8767-446add4afbcd.png)

**Comment by bobby-digital-23** [comment]
Glad you figured it out. 👍

Those simulator shortcuts can be both annoying and useful. I highly recommend learning as many as you can. My favorites are CMD + (1-3) because they change the size of the simulator screen which is very helpful for testing apps, particularly iPad apps, on a small laptop screen.

Let's hope that the simulator for the Apple Car will be easy to work with. 😉
ttp://www.macrumors.com/2015/02/13/apple-working-on-electric-car/
