### ISSUE TITLE
Final Project Comments

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#224]
I just wanted to say that the other instructors and I were all very impressed with the presentations last night.  They were by far the best we have seen yet.  Keep up the good work.

**Comment by bobby-digital-23** [comment]
Indeed, insanely great job everyone!

I hope that many of you have come to appreciate iOS development and Objective C.
Dr Binkowski made excellent points about the merits of the language and why he would choose to continue teaching it in the future.

After all of the work you've all put in, here's some random fun Objective C trivia:
The World Wide Web was created by Tim Berners-Lee on a NeXT machine in Objective C! The software tools he used were quite similar to what you have all been using these past several months (this is why you see NSWhatever and IBAction/IBOutlet all over the place in Xcode).

http://www.w3.org/People/Berners-Lee/WorldWideWeb.html

"I wrote the program using a NeXT computer. This had the advantage that there were some great tools available -it was a great computing environment in general. In fact, I could do in a couple of months what would take more like a year on other platforms, because on the NeXT, a lot of it was done for me already. There was an application builder to make all the menus as quickly as you could dream them up. there were all the software parts to make a wysiwyg (what you see is what you get - in other words direct manipulation of text on screen as on the printed - or browsed page) word processor. I just had to add hypertext, (by subclassing the Text object)" 
- Tim Berners-Lee

Please keep up the great work! Whenever you publish apps, definitely let us know. We're waiting for you to create the successor(s) to the World Wide Web. :)

**Comment by alextsu** [comment]
![image](https://cloud.githubusercontent.com/assets/6432040/6698943/6a91b188-cccb-11e4-922d-8758a4698d44.png)

**Comment by JRam13** [comment]
Ditto. 

I'm still waiting for Leo to win that Oscar :(
