### ISSUE TITLE
Purpose of Synthesize

### ISSUE THREAD

**Issue by yiqin** [uchicago-mobi/2015-Winter-Forum#25]
I get a question about synthesize. 

In the tutorial from Apple - Your First iOS App, the project use synthesize on Page 47:
// To synthesize the accessor methods for the user name property
@synthesize userName = _userName;

I think we don't need to use synthesize anymore, as Xcode will do synthesize automatically for us after iOS 6. The tutorial is updated in 2012-02-16. At that time, it's iOS 5. 

Is the synthesize necessary?

**Comment by bobby-digital-23** [comment]
Hi Yi,

You are correct, @synthesize is generally not required anymore when declaring properties.

This is getting ahead of ourselves since we have yet to really dig into ObjC but I say generally because there could come a time (rarely) when you will still want to use @synthesize: 
Nowadays, @synthesize is typically used when you want to create a different name for an ivar than the one LLVM compiler magically creates behind the scenes with modern @property syntax. In the old days (pre LLVM), you had to not only @synthesize all of your properties but you also had to manually declare all of your ivars - fun times. ;)

Hope that helps!
Bobby

**Comment by yiqin** [comment]
This is really helpful. Thanks.
