### ISSUE TITLE
If you "Download Zip" your project and your images/sounds aren't working...

### ISSUE THREAD

**Issue by alextsu** [uchicago-mobi/2015-Winter-Forum#56]
PSA: I tried downloading the .zip file of my completed project from GitHub and when I opened the files in xCode, the images and sound files for my project couldn't be found by xCode. I realized that dragging an image or sound into the xCode project only provides a filepath for xCode to access that resource. It does not copy and paste the resource into your project folder. 

If you encountered the same issue as me, you'll want to delete your image/sound references from GitHub. Next, you'll copy and paste those files somewhere in your project folder. Finally, you'll drag and drop those resource files into xCode. This ensures the referenced resource files are found within the project, and thus, will be accessible to our graders from GitHub.

**Comment by yiqin** [comment]
Could we update the repo now? Make another commit?

**Comment by tabinks** [comment]
This issue was addressed in issue #55 and #46 with references on how to correctly add resources to your project.  When adding resources, you to need to make sure that "Copy To Project" is selected and it will copy those files into your project bundle.

@yiqin You may go back and add references to your project.  Make sure you reference this in your commit.
