### ISSUE TITLE
Question Regarding the Assignment

### ISSUE THREAD

**Issue by myu5** [uchicago-mobi/2015-Winter-Forum#62]
Dear Instructors:

I have gotten my Assignment 2 grade, but not yet the Assignment 1 grade. Is it because of something wrong with my submission or it hasn't been graded yet?

**Comment by johnnypaper** [comment]
Where did you find your grade?

**Comment by myu5** [comment]
In the repository, there is another branch other than master called grade.

**Comment by johnnypaper** [comment]
Hmmm...I see.  I have the opposite situation of yours.  My first assignment is graded but my second is not, so I suppose it is just a matter of time for the grader to get to things.  I wouldn't worry about it.  But thanks for letting me know where the grades are.

**Comment by bobby-digital-23** [comment]
You will receive your grades for each assignment before the start of the next week's class, at the latest. Since assignment 2 was due this prior Monday you will receive your grade for it before start of class next Monday. If we have time we try to grade the assignments earlier...

Also, as Jonny noted in the other post, you will find your grade, with comments, in a branch under your master repo named "grade".

Another thing:
If you are using code from sources like Stack Overflow, blogs, Apple tutorials, etc then PLEASE document your comments properly by including URLs and notes. Clearly commenting your code helps us to understand your intent which allows us to grade your assignments more quickly. Commenting your code is a very important practice! Please keep in mind that we are all bound by the honor code.  

Best,
Bobby

**Comment by myu5** [comment]
I haven't get my Assignment 1 grade yet. Is there something wrong?
