### ISSUE TITLE
Where to put parsing code?

### ISSUE THREAD

**Issue by aljc** [uchicago-mobi/2015-Winter-Forum#87]
The instructions say "Download the issue data and load that table view when the data arrives."  I assume this means we have to download the data PRIOR to loading the table view, but our view controllers only come prepopulated with "viewDidLoad."  Does this mean we have to manually add a "viewWillAppear" function in our table view controllers (or in our navigation controllers?), or something of that nature?

**Comment by aljc** [comment]
Additionally, do you expect us to copy and paste the code into both table view controllers, or is there some sort of central place we can put it?

**Comment by tabinks** [comment]
The exact implementation details are up to you.  It would be a good practice to put the code in a separate class and call it from both view controllers.

You should call the networking code after the view loads, so that it doesn't block the view from appearing on screen.  A good place to do this would be `viewWillAppear` but it is really up to you to decide.  `viewDidLoad` is added as a convenience when you add a new view controller from Xcode.  You have to type out the other methods if you want to use them.

**Comment by JRam13** [comment]
> ...It would be a good practice to put the code in a separate class and call it from both view controllers.

This.

There are multiple ways of doing it this way- delegates, nsnotificationCenter, completionBlock (my favorite), etc. This is stuff that we'll eventually cover in class. It is not expected for this assignment, but I sure would be impressed if you guys took the time to implement it. 

**Completion block example...**

ViewController.m

``` obj-c
MyDataFetchClass *fetchData = [[MyDataFetchClass alloc] init];
    [fetchData fetchOpenIssues:^(BOOL success) {
        if (success) {
            //success! Update UI here
        }
        else{
            //something went wrong. no data?
        }
    }];
```

MyDataFetchClass.h

``` obj-c
@interface MyDataFetchClass : NSObject
-(void)fetchOpenIssues:(void (^)(BOOL success))completionBlock;
@end
```

MyDataFetchClass.m

``` obj-c
-(void)fetchOpenIssues:(void (^)(BOOL success))completionBlock
{
     //code here should be run in a background thread. Your main thread should not be blocked.
     //network CODE goes here (NSURLSession code).

          dispatch_async(dispatch_get_main_queue(), ^{
                 //back in the main thread. You may now update the UI!
                 completionBlock(YES); //Important. This will send the completion code back to the original class that called it along with the success boolean.
        });
    });
}
```

Really simple and clean. You can also pass multiple arguments inside the completion block, like an NSArray or NSDictionary, it doesn't have to be a BOOL **hint hint**.

**Comment by JRam13** [comment]
**Delegate example...**

ViewController.m

``` objc
@interface ViewController : UIViewController <DataFetchDelegate> //important
@end
@implementation ViewController

- (void)viewDidLoad
{
    [super viewDidLoad];

    MyDataFetchClass *fetchData = [[MyDataFetchClass alloc] init];
    fetchData.delegate = self;
    [fetchData startDataFetch];
}

//delegate
-(void)dataFetchCompleted:(NSMutableDictionary*)dataFetched
{
    //Update UI here
}
```

MyDataFetchClass.h

``` objc
@protocol DataFetchDelegate <NSObject>
@required //or @optional
- (void) dataFetchCompleted:(NSMutableDictionary*)dataFetched;
@end

@interface MyDataFetchClass : NSObject
@property (nonatomic, weak) id<DataFetchDelegate> delegate;
-(void)startDataFetch; 

@end
```

MyDataFetchClass.m

``` objc
@implementation MyDataFetchClass

-(void)startDataFetch
{
     //code here should be run in a background thread. Your main thread should not be blocked.
     //network CODE goes here (NSURLSession code).

          dispatch_async(dispatch_get_main_queue(), ^{
                 //back in the main thread. You may now update the UI!
                [self.delegate dataFetchCompleted:myDictionaryOfData];
        });
    });
}
@end
```

**Comment by JRam13** [comment]
Personally I love the completion block style- all you really do is add :(void (^)(YourParam)) at the end of a method name and you have yourself a completion block. The drawback is that block syntax is weird. 

The delegate route is the formal way- since objC was built around the delegate pattern. However, I do feel like there is too much going on and you have to be careful defining your protocols correctly.

I found a really good answer to the blocks vs delegates debate on quora, which pretty much expresses how I feel about the issue.

> Brian Papa
> Brian Papa, App Maker
> If you find yourself only needing to write a couple of delegate methods to define a protocol, you might want to use a block instead. Before blocks, I needed to write code in 4 different files to properly handle a network operation, when at the heart of it I only needed to write a couple of lines to update UI, navigate to a new View Controller, or show an alert. Blocks are a big win there.
> 
> If a block becomes unwieldily because there are many different code paths inside of it, it's probably worth considering creating a protocol and using a delegate instead. Imagine if UITableViewDelegate was replaced with a bunch of block implementations? Yikes.
> 
> Also delegate protocols can be applied to many different classes which each provide their own implementations. Blocks can't be used in the same way.
> 
> In short, I'd say use blocks when you can. When you can't, consider using a delegate.
> 
> Written 17 Jun, 2013.

http://www.quora.com/When-and-why-should-one-use-blocks-vs-delegates-in-Objective-C

PS: I understand this might go over everyone's head here, it's way too early to start thinking about this sort of stuff. However, exposure is always good. I also feel like this would be something you guys will come back to in the near future.

**Comment by aljc** [comment]
This is really thorough, thanks!
