### ISSUE TITLE
drawRect not showing?

### ISSUE THREAD

**Issue by aljc** [uchicago-mobi/2015-Winter-Forum#99]
I overrode the drawRect method in my CircleViewController with a custom method that's supposed to draw a circle.  I then called [self.view setsNeedsDisplay] in my viewDidLoad for that class, which I understand makes a call to drawRect.  However, nothing is showing up.  What should I be doing instead?

**Comment by tabinks** [comment]
You need to implement `drawRect:` inside a custom view _not_ in the view controller.  Create a new custom class of type `UIView`.  Implement `drawRect:` in that class.  Add your custom `UIView` to the view controller.  You shouldn't need to explicitly call `setNeedsDisplay`.  The `drawRect:` will be called when you add the subview to the view controller.  `setNeedsDisplay` is for when you need something redrawn.

**Comment by aljc** [comment]
So I moved the custom drawRect class inside a custom UIView, named DrawCircle.  I then imported and added that view into my CircleViewController by calling allocing and initializing the DrawCircle object, and calling [self.view addSubview:...] inside viewDidLoad inside the view controller.  But there's still nothing showing up?

**Comment by tabinks** [comment]
That sounds about right.  If you did everything you said, then its a problem with your drawing code.  One good debugging tip is to change the color of your `UIView`s while developing so that you can actually verify that they are on the screen.  If you see the colored square then you know its there...then you can move on to debugging your drawing code.
